from __future__ import annotations

import json
from pathlib import Path

from .features import FeaturePlan
from .rig import Bone


def write_blender_script(
    output: Path,
    *,
    obj_path: Path,
    bones: list[Bone],
    group_to_bone: dict[str, str],
    smooth_weights: bool = True,
    glb_path: Path | None = None,
    vrm_path: Path | None = None,
    features: FeaturePlan | None = None,
    accessory_physics: bool = True,
    expression_scaffold: bool = True,
    model_name: str = "RobloxAvatar",
) -> None:
    feature_data = features.to_dict() if features else {
        "eyes": None, "dynamic_accessories": [], "expression_presets": [],
        "native_expression_source": False, "expression_mode": "disabled",
    }
    data = {
        "obj": str(Path(obj_path).resolve()),
        "bones": [{"name": b.name, "parent": b.parent, "position": list(b.position)} for b in bones],
        "group_to_bone": group_to_bone,
        "smooth_weights": bool(smooth_weights),
        "glb_path": str(Path(glb_path).resolve()) if glb_path else None,
        "vrm_path": str(Path(vrm_path).resolve()) if vrm_path else None,
        "features": feature_data,
        "accessory_physics": bool(accessory_physics),
        "expression_scaffold": bool(expression_scaffold),
        "model_name": model_name,
    }
    payload = json.dumps(data, ensure_ascii=False)
    template = r'''# Generated by Roblox Avatar Conversion Kit v0.3
import bpy, json, math, re
from mathutils import Vector

DATA = json.loads(__PAYLOAD__)

def dist(a, b):
    return (a - b).length

def point_segment_distance(p, a, b):
    ab = b - a
    denom = ab.length_squared
    if denom <= 1e-12:
        return (p - a).length
    t = max(0.0, min(1.0, (p - a).dot(ab) / denom))
    return (p - (a + ab * t)).length

def clean_obj_name(name):
    base = re.sub(r"\.\d{3}$", "", name)
    if base in DATA["group_to_bone"]:
        return base
    for group in DATA["group_to_bone"]:
        if base.startswith(group):
            return group
    return base

bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete(use_global=False)
try:
    bpy.ops.wm.obj_import(filepath=DATA["obj"])
except Exception:
    bpy.ops.import_scene.obj(filepath=DATA["obj"])
meshes = [obj for obj in bpy.context.scene.objects if obj.type == "MESH"]

base_specs = list(DATA["bones"])
all_specs = list(base_specs)
eyes = DATA["features"].get("eyes")
if eyes:
    all_specs.extend([
        {"name":"eyes", "parent":"head", "position":eyes["master_position"]},
        {"name":"leftEye", "parent":"eyes", "position":eyes["left_position"]},
        {"name":"rightEye", "parent":"eyes", "position":eyes["right_position"]},
    ])
if DATA["accessory_physics"]:
    for dynamic in DATA["features"].get("dynamic_accessories", []):
        all_specs.append({"name":dynamic["bone_name"], "parent":dynamic["parent_bone"], "position":dynamic["root_position"]})
        all_specs.append({"name":dynamic["terminal_name"], "parent":dynamic["bone_name"], "position":dynamic["tail_position"]})

arm_data = bpy.data.armatures.new("RobloxAvatarRig")
arm_obj = bpy.data.objects.new("RobloxAvatarRig", arm_data)
bpy.context.collection.objects.link(arm_obj)
bpy.context.view_layer.objects.active = arm_obj
arm_obj.select_set(True)
bpy.ops.object.mode_set(mode="EDIT")
created = {}
all_by_name = {spec["name"]: spec for spec in all_specs}
all_children = {name: [] for name in all_by_name}
for spec in all_specs:
    if spec["parent"] in all_children:
        all_children[spec["parent"]].append(spec["name"])
for spec in all_specs:
    bone = arm_data.edit_bones.new(spec["name"])
    bone.head = Vector(spec["position"])
    created[spec["name"]] = bone
for spec in all_specs:
    bone = created[spec["name"]]
    kids = all_children.get(spec["name"], [])
    if kids:
        child = min(kids, key=lambda name: dist(bone.head, Vector(all_by_name[name]["position"])))
        tail = Vector(all_by_name[child]["position"])
    elif spec["parent"] and spec["parent"] in all_by_name:
        parent = Vector(all_by_name[spec["parent"]]["position"])
        direction = bone.head - parent
        tail = bone.head + (direction * 0.35 if direction.length > 1e-5 else Vector((0, 0.1, 0)))
    else:
        tail = bone.head + Vector((0, 0.1, 0))
    if (tail - bone.head).length < 1e-4:
        tail = bone.head + Vector((0, 0.1, 0))
    bone.tail = tail
for spec in all_specs:
    if spec["parent"]:
        created[spec["name"]].parent = created.get(spec["parent"])
bpy.ops.object.mode_set(mode="OBJECT")

# Keep smooth skin calculations restricted to the original humanoid skeleton.
by_name = {spec["name"]: spec for spec in base_specs}
children = {name: [] for name in by_name}
for spec in base_specs:
    if spec["parent"] in children:
        children[spec["parent"]].append(spec["name"])
bone_pos = {name: Vector(spec["position"]) for name, spec in by_name.items()}
segments = {}
for name, spec in by_name.items():
    kids = children.get(name, [])
    if kids:
        child = min(kids, key=lambda candidate: dist(bone_pos[name], bone_pos[candidate]))
        segments[name] = (bone_pos[name], bone_pos[child])
    elif spec["parent"] in bone_pos:
        direction = bone_pos[name] - bone_pos[spec["parent"]]
        segments[name] = (bone_pos[name], bone_pos[name] + direction * 0.35)
    else:
        segments[name] = (bone_pos[name], bone_pos[name] + Vector((0, 0.1, 0)))

def candidates(primary):
    names = [primary]
    spec = by_name.get(primary)
    if spec and spec["parent"]:
        names.append(spec["parent"])
    names.extend(children.get(primary, []))
    if primary in {"hips", "spine", "chest", "neck"}:
        names.extend([name for name in ("hips", "spine", "chest", "neck") if name in by_name])
    result = []
    for name in names:
        if name in by_name and name not in result:
            result.append(name)
    return result

def point_weights(point, primary):
    scored = []
    for name in candidates(primary):
        a, b = segments[name]
        length = max((b - a).length, 0.15)
        distance = point_segment_distance(point, a, b)
        score = 1.0 / ((distance + 0.20 * length) ** 2)
        if name == primary:
            score *= 1.35
        scored.append((name, score))
    scored.sort(key=lambda item: item[1], reverse=True)
    scored = scored[:4]
    total = sum(score for _, score in scored) or 1.0
    normalized = [(name, score / total) for name, score in scored]
    normalized = [(name, weight) for name, weight in normalized if weight >= 0.025] or [max(normalized, key=lambda item: item[1])]
    total = sum(weight for _, weight in normalized) or 1.0
    return [(name, weight / total) for name, weight in normalized]

effective_mapping = dict(DATA["group_to_bone"])
if DATA["accessory_physics"]:
    for dynamic in DATA["features"].get("dynamic_accessories", []):
        effective_mapping[dynamic["group"]] = dynamic["bone_name"]

weighted_vertices = 0
head_mesh = None
for obj in meshes:
    obj.parent = arm_obj
    obj.modifiers.new(name="Armature", type="ARMATURE").object = arm_obj
    group = clean_obj_name(obj.name)
    original_primary = DATA["group_to_bone"].get(group)
    primary = effective_mapping.get(group)
    if original_primary == "head" and group.lower().startswith("rig") and head_mesh is None:
        head_mesh = obj
    if not primary:
        continue
    smooth = DATA["smooth_weights"] and group.lower().startswith("rig")
    groups = {}
    def vertex_group(name):
        if name not in groups:
            groups[name] = obj.vertex_groups.get(name) or obj.vertex_groups.new(name=name)
        return groups[name]
    if not smooth or primary not in by_name:
        vertex_group(primary).add(list(range(len(obj.data.vertices))), 1.0, "REPLACE")
        weighted_vertices += len(obj.data.vertices)
        continue
    for vertex in obj.data.vertices:
        point = obj.matrix_world @ vertex.co
        for bone_name, weight in point_weights(point, primary):
            vertex_group(bone_name).add([vertex.index], weight, "REPLACE")
        weighted_vertices += 1

# OBJ has no native shape-key deltas. Generate a standard, editable zero-delta scaffold instead of
# fabricating facial deformation that could damage a texture-based Roblox face.
expression_scaffolded = False
if DATA["expression_scaffold"] and head_mesh:
    if not head_mesh.data.shape_keys:
        head_mesh.shape_key_add(name="Basis", from_mix=False)
    for expression_name in DATA["features"].get("expression_presets", []):
        if expression_name not in head_mesh.data.shape_keys.key_blocks:
            head_mesh.shape_key_add(name=expression_name, from_mix=False)
    expression_scaffolded = True

vrm_configured = False
look_at_configured = False
spring_count = 0
expression_bind_count = 0
try:
    arm_data.vrm_addon_extension.spec_version = "1.0"
    extension = arm_data.vrm_addon_extension
    vrm1 = extension.vrm1
    human = vrm1.humanoid.human_bones
    for name in ["hips","spine","chest","neck","head","leftEye","rightEye","leftUpperArm","leftLowerArm","leftHand","rightUpperArm","rightLowerArm","rightHand","leftUpperLeg","leftLowerLeg","leftFoot","rightUpperLeg","rightLowerLeg","rightFoot"]:
        if name not in all_by_name:
            continue
        try:
            getattr(human, name).node.bone_name = name
        except Exception:
            pass
    try:
        meta = vrm1.meta
        meta.vrm_name = DATA["model_name"]
        meta.version = "0.3.0"
        if len(meta.authors) == 0:
            meta.authors.add().value = "Avatar owner"
    except Exception:
        pass
    if eyes:
        try:
            look_at = vrm1.look_at
            look_at.type = "bone"
            head = Vector(eyes["head_position"])
            master = Vector(eyes["master_position"])
            look_at.offset_from_head_bone = tuple(master - head)
            for range_map in (
                look_at.range_map_horizontal_inner, look_at.range_map_horizontal_outer,
                look_at.range_map_vertical_down, look_at.range_map_vertical_up,
            ):
                range_map.input_max_value = 45.0
                range_map.output_scale = 15.0
            look_at_configured = True
        except Exception as error:
            print("WARNING: VRM LookAt setup skipped:", error)
    if expression_scaffolded and head_mesh:
        attr_map = {"blinkLeft":"blink_left", "blinkRight":"blink_right"}
        for expression_name in DATA["features"].get("expression_presets", []):
            try:
                expression = getattr(vrm1.expressions.preset, attr_map.get(expression_name, expression_name))
                bind = expression.morph_target_binds.add()
                bind.node.mesh_object_name = head_mesh.name
                bind.index = expression_name
                bind.weight = 1.0
                expression_bind_count += 1
            except Exception:
                pass
    if DATA["accessory_physics"] and DATA["features"].get("dynamic_accessories"):
        try:
            from io_scene_vrm.common import ops as vrm_ops
            spring_bone1 = extension.spring_bone1
            for dynamic in DATA["features"]["dynamic_accessories"]:
                spring_index = len(spring_bone1.springs)
                result = vrm_ops.vrm.add_spring_bone1_spring(armature_object_name=arm_obj.name)
                if result != {"FINISHED"}:
                    continue
                spring = spring_bone1.springs[spring_index]
                spring.vrm_name = dynamic["name"]
                joint = spring.add_joint()
                joint.node.bone_name = dynamic["bone_name"]
                joint.stiffness = dynamic["stiffness"]
                joint.drag_force = dynamic["drag_force"]
                joint.gravity_power = dynamic["gravity_power"]
                joint.gravity_dir = (0.0, -1.0, 0.0)
                joint.hit_radius = max(0.01, min(dynamic["size"]) * 0.08)
                terminal = spring.add_joint()
                terminal.node.bone_name = dynamic["terminal_name"]
                spring_count += 1
        except Exception as error:
            print("WARNING: VRM SpringBone setup skipped:", error)
    vrm_configured = True
except Exception as error:
    print("WARNING: VRM Add-on not available or could not be configured:", error)

def arm_drop(side):
    upper = bone_pos.get(side + "UpperArm")
    lower = bone_pos.get(side + "LowerArm")
    if not upper or not lower:
        return None
    vector = lower - upper
    horizontal = abs(vector.x) + abs(vector.z)
    return math.degrees(math.atan2(abs(vector.y), max(horizontal, 1e-6)))
pose_warnings = []
for side in ("left", "right"):
    angle = arm_drop(side)
    if angle is not None and angle > 20.0:
        pose_warnings.append("%s arm rest pose drops %.1f degrees; normalize to T/A-pose before production VRM export." % (side, angle))

if DATA.get("glb_path"):
    bpy.context.view_layer.objects.active = arm_obj
    bpy.ops.export_scene.gltf(filepath=DATA["glb_path"], export_format="GLB", export_skins=True, export_morph=True)
    print("Roblox Avatar Conversion Kit: exported GLB ->", DATA["glb_path"])
if DATA.get("vrm_path"):
    if vrm_configured:
        try:
            bpy.context.view_layer.objects.active = arm_obj
            arm_obj.select_set(True)
            result = bpy.ops.export_scene.vrm(filepath=DATA["vrm_path"])
            print("Roblox Avatar Conversion Kit: VRM export", result, "->", DATA["vrm_path"])
        except Exception as error:
            print("WARNING: automatic VRM export failed:", error)
    else:
        print("WARNING: --vrm requested but the VRM Add-on is not configured.")

print("Roblox Avatar Conversion Kit: scene built; weighted %d vertices; VRM=%s; LookAt=%s; springs=%d; expression binds=%d" % (weighted_vertices, vrm_configured, look_at_configured, spring_count, expression_bind_count))
if expression_scaffolded and not DATA["features"].get("native_expression_source"):
    print("NOTICE: facial expression shape keys are zero-delta editable scaffolds because OBJ contains no source morph deltas.")
for warning in pose_warnings:
    print("WARNING:", warning)
print("Review reconstructed weights, physics, facial shape keys, and rest pose before production use.")
'''
    script = template.replace("__PAYLOAD__", repr(payload))
    Path(output).write_text(script, encoding="utf-8")
