from __future__ import annotations

import json
from pathlib import Path

from .rig import Bone


def write_blender_script(output: Path, *, obj_path: Path, bones: list[Bone], group_to_bone: dict[str, str]) -> None:
    data = {
        "obj": str(Path(obj_path).resolve()),
        "bones": [{"name": b.name, "parent": b.parent, "position": list(b.position)} for b in bones],
        "group_to_bone": group_to_bone,
    }
    payload = json.dumps(data, ensure_ascii=False)
    script = f'''# Generated by Roblox Avatar Conversion Kit\nimport bpy, json\nfrom mathutils import Vector\n\nDATA = json.loads({payload!r})\n\nbpy.ops.object.select_all(action="SELECT")\nbpy.ops.object.delete(use_global=False)\n\ntry:\n    bpy.ops.wm.obj_import(filepath=DATA["obj"])\nexcept Exception:\n    bpy.ops.import_scene.obj(filepath=DATA["obj"])\n\nmeshes = [o for o in bpy.context.scene.objects if o.type == "MESH"]\n\narm_data = bpy.data.armatures.new("RobloxAvatarRig")\narm_obj = bpy.data.objects.new("RobloxAvatarRig", arm_data)\nbpy.context.collection.objects.link(arm_obj)\nbpy.context.view_layer.objects.active = arm_obj\narm_obj.select_set(True)\nbpy.ops.object.mode_set(mode="EDIT")\ncreated = {{}}\nfor spec in DATA["bones"]:\n    b = arm_data.edit_bones.new(spec["name"])\n    b.head = Vector(spec["position"])\n    b.tail = b.head + Vector((0, 0.12, 0))\n    created[spec["name"]] = b\nfor spec in DATA["bones"]:\n    if spec["parent"]:\n        created[spec["name"]].parent = created.get(spec["parent"])\nbpy.ops.object.mode_set(mode="OBJECT")\n\nfor obj in meshes:\n    obj.parent = arm_obj\n    obj.modifiers.new(name="Armature", type="ARMATURE").object = arm_obj\n    bone_name = DATA["group_to_bone"].get(obj.name)\n    if bone_name:\n        vg = obj.vertex_groups.new(name=bone_name)\n        vg.add(list(range(len(obj.data.vertices))), 1.0, "REPLACE")\n\ntry:\n    arm_data.vrm_addon_extension.spec_version = "1.0"\n    human = arm_data.vrm_addon_extension.vrm1.humanoid.human_bones\n    for name in ["hips","spine","chest","neck","head","leftUpperArm","leftLowerArm","leftHand","rightUpperArm","rightLowerArm","rightHand","leftUpperLeg","leftLowerLeg","leftFoot","rightUpperLeg","rightLowerLeg","rightFoot"]:\n        try:\n            getattr(human, name).node.bone_name = name\n        except Exception:\n            pass\nexcept Exception:\n    pass\n\nprint("Roblox Avatar Conversion Kit: scene built. Review weights before final VRM/PMX export.")\n'''
    Path(output).write_text(script, encoding="utf-8")
