from __future__ import annotations

import struct
from collections import defaultdict
from pathlib import Path

from .obj import Material, ObjMesh
from .rig import Bone


def _text(value: str) -> bytes:
    raw = value.encode("utf-8")
    return struct.pack("<i", len(raw)) + raw


def _vec2(v):
    return struct.pack("<2f", *v)


def _vec3(v):
    return struct.pack("<3f", *v)


def _vec4(v):
    return struct.pack("<4f", *v)


def _mmd_vec3(v: tuple[float, float, float]) -> tuple[float, float, float]:
    return (v[0], v[1], -v[2])


def write_pmx(
    output: Path,
    *,
    model_name: str,
    mesh: ObjMesh,
    materials: dict[str, Material],
    bones: list[Bone],
    group_to_bone: dict[str, str],
) -> dict:
    bone_index = {b.name: i for i, b in enumerate(bones)}
    textures: list[str] = []
    for m in materials.values():
        if m.map_kd and m.map_kd not in textures:
            textures.append(m.map_kd)
    texture_index = {name: i for i, name in enumerate(textures)}

    vertex_map: dict[tuple, int] = {}
    out_vertices: list[tuple] = []
    indices_by_material: dict[str | None, list[int]] = defaultdict(list)

    for face in mesh.faces:
        face_indices: list[int] = []
        for vi, ti, ni in face.corners:
            key = (vi, ti, ni, face.group)
            if key not in vertex_map:
                pos = _mmd_vec3(mesh.vertices[vi])
                uv = mesh.uvs[ti] if ti is not None and 0 <= ti < len(mesh.uvs) else (0.0, 0.0)
                normal = _mmd_vec3(mesh.normals[ni]) if ni is not None and 0 <= ni < len(mesh.normals) else (0.0, 1.0, 0.0)
                bone = bone_index.get(group_to_bone.get(face.group, "spine"), bone_index.get("spine", 0))
                vertex_map[key] = len(out_vertices)
                out_vertices.append((pos, normal, uv, bone))
            face_indices.append(vertex_map[key])
        indices_by_material[face.material].extend(reversed(face_indices))

    material_order = list(dict.fromkeys(face.material for face in mesh.faces))
    blob = bytearray()
    blob += b"PMX "
    blob += struct.pack("<f", 2.0)
    blob += struct.pack("<B", 8)
    blob += bytes([1, 0, 4, 4, 4, 4, 4, 4])
    blob += _text(model_name)
    blob += _text(model_name)
    blob += _text("Generated by Roblox Avatar Conversion Kit. Reconstructed weights are approximate.")
    blob += _text("Generated by Roblox Avatar Conversion Kit. Reconstructed weights are approximate.")

    blob += struct.pack("<i", len(out_vertices))
    for pos, normal, uv, bone in out_vertices:
        blob += _vec3(pos) + _vec3(normal) + _vec2(uv)
        blob += struct.pack("<B", 0)
        blob += struct.pack("<i", bone)
        blob += struct.pack("<f", 1.0)

    flat_indices = [i for mat in material_order for i in indices_by_material[mat]]
    blob += struct.pack("<i", len(flat_indices))
    for idx in flat_indices:
        blob += struct.pack("<I", idx)

    blob += struct.pack("<i", len(textures))
    for texture in textures:
        blob += _text(texture)

    blob += struct.pack("<i", len(material_order))
    for n, mat_name in enumerate(material_order):
        mat = materials.get(mat_name or "") or Material(mat_name or f"Material{n + 1}")
        blob += _text(mat.name) + _text(mat.name)
        blob += _vec4((*mat.kd, mat.alpha))
        blob += _vec3(mat.ks)
        blob += struct.pack("<f", max(0.0, mat.ns))
        blob += _vec3(tuple(c * 0.5 for c in mat.kd))
        blob += struct.pack("<B", 0x1F)
        blob += _vec4((0.0, 0.0, 0.0, 1.0))
        blob += struct.pack("<f", 1.0)
        blob += struct.pack("<i", texture_index.get(mat.map_kd, -1))
        blob += struct.pack("<i", -1)
        blob += struct.pack("<B", 0)
        blob += struct.pack("<B", 1)
        blob += struct.pack("<B", 0)
        blob += _text("")
        blob += struct.pack("<i", len(indices_by_material[mat_name]))

    blob += struct.pack("<i", len(bones))
    for bone in bones:
        parent = bone_index.get(bone.parent, -1) if bone.parent else -1
        blob += _text(bone.name) + _text(bone.name)
        blob += _vec3(_mmd_vec3(bone.position))
        blob += struct.pack("<i", parent)
        blob += struct.pack("<i", 0)
        flags = 0x001A
        if bone.name == "hips":
            flags |= 0x0004
        blob += struct.pack("<H", flags)
        blob += _vec3((0.0, 0.1, 0.0))

    blob += struct.pack("<i", 0)
    blob += struct.pack("<i", 0)
    blob += struct.pack("<i", 0)
    blob += struct.pack("<i", 0)

    Path(output).write_bytes(blob)
    return {
        "vertices": len(out_vertices),
        "triangles": len(flat_indices) // 3,
        "materials": len(material_order),
        "textures": len(textures),
        "bones": len(bones),
        "bytes": len(blob),
    }
